import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './.storybook/preview.tsx',
  ],
  safelist: [
    //slider conditional color
    'active:bg-danger-600',
    'active:bg-primary-600',
    'active:text-danger-600',
    'active:text-neutral-600',
    'active:text-primary-600',
    'bg-danger-500',
    'bg-primary-400',
    'bg-primary-500',
    'bg-primary-600',
    'bg-secondary-400',
    'bg-secondary-600',
    'bg-tertiary-400',
    'bg-tertiary-600',
    'text-danger-500',
    'text-neutral-500',
    'text-primary-500',
    'hover:bg-primary-500',
    'hover:bg-secondary-500',
    'hover:bg-tertiary-500',
    'hover:bg-danger-500/90',
    'hover:bg-primary-500/90',
    'hover:text-danger-500/70',
    'hover:text-neutral-500/70',
    'hover:text-primary-500/70',
    'hover:bg-primary-700',
    'hover:bg-secondary-700',
    'hover:bg-tertiary-700',
    'focus:ring-danger-600',
    'focus:ring-danger-800',
    'focus:ring-neutral-600',
    'focus:ring-primary-600',
    'focus:ring-primary-800',
    'focus-visible:ring-primary-500',
    'focus-visible:ring-secondary-500',
    'focus-visible:ring-tertiary-500',
    'peer-focus:ring-primary-500',
    'peer-focus:ring-secondary-500',
    'peer-focus:ring-tertiary-500',
    'peer-checked:bg-primary-600',
    'peer-checked:bg-secondary-600',
    'peer-checked:bg-tertiary-600',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      'most-contrast': 'rgb(var(--most-contrast) / <alpha-value>)',
      'least-contrast': 'rgb(var(--least-contrast) / <alpha-value>)',
      primary: {
        50: 'rgb(var(--primary-50) / <alpha-value>)',
        100: 'rgb(var(--primary-100) / <alpha-value>)',
        200: 'rgb(var(--primary-200) / <alpha-value>)',
        300: 'rgb(var(--primary-300) / <alpha-value>)',
        400: 'rgb(var(--primary-400) / <alpha-value>)',
        500: 'rgb(var(--primary-500) / <alpha-value>)',
        600: 'rgb(var(--primary-600) / <alpha-value>)',
        700: 'rgb(var(--primary-700) / <alpha-value>)',
        800: 'rgb(var(--primary-800) / <alpha-value>)',
        900: 'rgb(var(--primary-900) / <alpha-value>)',
      },
      secondary: {
        50: 'rgb(var(--secondary-50) / <alpha-value>)',
        100: 'rgb(var(--secondary-100) / <alpha-value>)',
        200: 'rgb(var(--secondary-200) / <alpha-value>)',
        300: 'rgb(var(--secondary-300) / <alpha-value>)',
        400: 'rgb(var(--secondary-400) / <alpha-value>)',
        500: 'rgb(var(--secondary-500) / <alpha-value>)',
        600: 'rgb(var(--secondary-600) / <alpha-value>)',
        700: 'rgb(var(--secondary-700) / <alpha-value>)',
        800: 'rgb(var(--secondary-800) / <alpha-value>)',
        900: 'rgb(var(--secondary-900) / <alpha-value>)',
      },
      tertiary: {
        50: 'rgb(var(--tertiary-50) / <alpha-value>)',
        100: 'rgb(var(--tertiary-100) / <alpha-value>)',
        200: 'rgb(var(--tertiary-200) / <alpha-value>)',
        300: 'rgb(var(--tertiary-300) / <alpha-value>)',
        400: 'rgb(var(--tertiary-400) / <alpha-value>)',
        500: 'rgb(var(--tertiary-500) / <alpha-value>)',
        600: 'rgb(var(--tertiary-600) / <alpha-value>)',
        700: 'rgb(var(--tertiary-700) / <alpha-value>)',
        800: 'rgb(var(--tertiary-800) / <alpha-value>)',
        900: 'rgb(var(--tertiary-900) / <alpha-value>)',
      },
      neutral: {
        50: 'rgb(var(--neutral-50) / <alpha-value>)',
        100: 'rgb(var(--neutral-100) / <alpha-value>)',
        200: 'rgb(var(--neutral-200) / <alpha-value>)',
        300: 'rgb(var(--neutral-300) / <alpha-value>)',
        400: 'rgb(var(--neutral-400) / <alpha-value>)',
        500: 'rgb(var(--neutral-500) / <alpha-value>)',
        600: 'rgb(var(--neutral-600) / <alpha-value>)',
        700: 'rgb(var(--neutral-700) / <alpha-value>)',
        800: 'rgb(var(--neutral-800) / <alpha-value>)',
        900: 'rgb(var(--neutral-900) / <alpha-value>)',
      },
      danger: {
        50: 'rgb(var(--danger-50) / <alpha-value>)',
        100: 'rgb(var(--danger-100) / <alpha-value>)',
        200: 'rgb(var(--danger-200) / <alpha-value>)',
        300: 'rgb(var(--danger-300) / <alpha-value>)',
        400: 'rgb(var(--danger-400) / <alpha-value>)',
        500: 'rgb(var(--danger-500) / <alpha-value>)',
        600: 'rgb(var(--danger-600) / <alpha-value>)',
        700: 'rgb(var(--danger-700) / <alpha-value>)',
        800: 'rgb(var(--danger-800) / <alpha-value>)',
        900: 'rgb(var(--danger-900) / <alpha-value>)',
      },
      success: {
        50: 'rgb(var(--success-50) / <alpha-value>)',
        100: 'rgb(var(--success-100) / <alpha-value>)',
        200: 'rgb(var(--success-200) / <alpha-value>)',
        300: 'rgb(var(--success-300) / <alpha-value>)',
        400: 'rgb(var(--success-400) / <alpha-value>)',
        500: 'rgb(var(--success-500) / <alpha-value>)',
        600: 'rgb(var(--success-600) / <alpha-value>)',
        700: 'rgb(var(--success-700) / <alpha-value>)',
        800: 'rgb(var(--success-800) / <alpha-value>)',
        900: 'rgb(var(--success-900) / <alpha-value>)',
      },
    },
    extend: {
      fontSize: {
        xxs: '.625rem',
      },
      transitionDuration: {
        DEFAULT: '250ms',
      },
    },
  },
  plugins: [],
}

export default config
